import Head from "next/head";
import { Nav, Hero, About, Skills, Projects, Contacts } from "./components";

export default function Home() {
    return (
        <div className="flex min-h-screen flex-col font-chakra transition-colors duration-500 ease-in bg-theme-light dark:bg-theme-dark">
            <Head>
                <title>Create Next App</title>
                {/* <meta
                    name="description"
                    content="Generated by create next app"
                /> */}
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="max-w-[1152px] w-full mx-auto">
                <Nav />
                <Hero />
                <About />
                <Skills />
                <Projects />
                <Contacts />
            </main>
        </div>
    );
}
