import Head from "next/head";
import { Nav, Hero, About, Skills, Projects, Contacts } from "./components";
import ParticlesBackground from "./components/ParticlesBackground";

export default function Home() {
  return (
    <div className="flex min-h-screen flex-col font-inter transition-colors duration-500 ease-in ">
      <Head>
        <title>Javi Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <div className="h-screen w-full bg-transparent">
      </div> */}
      <ParticlesBackground />
      <main className="max-w-[1280px] w-full mx-auto h-full relative">
        {/* <Nav/> */}
        <Hero />
      </main>
    </div>
  );
}
